import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {BtnSecondary} from '@/shared/ui/admin/AdminLayout';
import {deliveryLabel,friendlyEntries} from '../domain/resource-ui.mjs';
import {operateSacDigitalResource} from '../infrastructure/sac-digital.repository';
export function SacDigitalDeliveryHistory({organizationId}:{organizationId:string}) {
 const [kind,setKind]=useState<'delivery_history'|'sms_replies'>('delivery_history');const [page,setPage]=useState(1);
 const [rows,setRows]=useState<any[]>([]),[more,setMore]=useState(false),[error,setError]=useState('');const [checking,setChecking]=useState<string|null>(null);
 useEffect(()=>{let alive=true,inFlight=false;async function load(){if(inFlight||document.visibilityState!=='visible')return;inFlight=true;try{const {data,error}=await supabase.functions.invoke('sac-digital-api',{body:{action:kind,organization_id:organizationId,page}});if(error||!data?.success)throw Error(data?.error||'Não foi possível carregar o histórico.');if(alive){setRows(data.data.list);setMore(data.has_more);setError('');}}catch(e){if(alive)setError(e instanceof Error?e.message:'Não foi possível carregar o histórico.');}finally{inFlight=false;}}void load();const timer=window.setInterval(load,60000);return()=>{alive=false;clearInterval(timer);};},[organizationId,kind,page]);
 async function inspect(row:any){setChecking(row.id);try{const result=await operateSacDigitalResource(organizationId,41,{id:row.notification_id});const entries=friendlyEntries(result.data);setError(entries.map(([label,value]:any)=>`${label}: ${typeof value==='object'?'Disponível':String(value)}`).join(' · ')||'A SAC recebeu a consulta. A entrega só aparece quando confirmada.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível consultar esta notificação.');}finally{setChecking(null);}}
 return <section aria-label="Histórico de envios" className="mt-4 space-y-3 rounded border border-border bg-card p-4"><div className="flex gap-2"><BtnSecondary onClick={()=>{setKind('delivery_history');setPage(1);}}>Histórico de envios</BtnSecondary><BtnSecondary onClick={()=>{setKind('sms_replies');setPage(1);}}>Respostas SMS</BtnSecondary></div><p className="text-sm text-muted-foreground">Cada tentativa permanece registrada. Aceite e fila não confirmam entrega.</p>{error&&<p role="status" className="text-sm">{error}</p>}{rows.length===0?<p className="text-sm">Nenhum registro nesta página.</p>:rows.map((row:any)=><article key={row.id||row.source_event_hash} className="rounded border border-border p-3 text-sm">{kind==='delivery_history'?<><p><strong>{deliveryLabel({delivery_status:row.state})}</strong> · {new Date(row.created_at).toLocaleString('pt-BR')}</p>{row.protocol&&<p>Protocolo: {row.protocol}</p>}{row.notification_id&&<><p>Notificação: {row.notification_id}</p><BtnSecondary disabled={checking===row.id} onClick={()=>void inspect(row)}>Consultar confirmação</BtnSecondary></>}{row.message_id&&<p>Mensagem: {row.message_id}</p>}{row.error_type&&<p>Falha: {row.error_type}</p>}</>:<><p>{new Date(row.received_at).toLocaleString('pt-BR')}</p>{friendlyEntries(row.payload).map(([label,value]:any)=><p key={label}>{label}: {typeof value==='object'?'Resposta recebida':String(value)}</p>)}</>}</article>)}<div className="flex items-center gap-3"><BtnSecondary disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</BtnSecondary><span className="text-sm">Página {page}</span><BtnSecondary disabled={!more} onClick={()=>setPage(p=>p+1)}>Próxima</BtnSecondary></div></section>;
}
