import {useEffect,useState} from 'react';
import {AdminButton,BtnSecondary} from '@/shared/ui/admin/AdminLayout';
import {configureSacDigitalMenu,getSacDigitalMenuSettings,getSacDigitalResourceHealth,sacDigitalMenuUrl,type SacDigitalMenuSettings} from '../infrastructure/sac-digital.repository';
export function SacDigitalMenuConfiguration({organizationId,token}:{organizationId:string;token?:string|null}) {
 const [settings,setSettings]=useState<SacDigitalMenuSettings>({enabled:false,text:'',choices:[],source:'static'});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [health,setHealth]=useState<Record<string,unknown>|null>(null);
 useEffect(()=>{let active=true;getSacDigitalMenuSettings(organizationId).then(data=>{if(active)setSettings(data);}).catch(e=>{if(active)setError(e.message);});getSacDigitalResourceHealth(organizationId).then(data=>{if(active)setHealth(data);}).catch(()=>{});return()=>{active=false;};},[organizationId]);
 const save=async()=>{setBusy(true);setError('');setNotice('');try{setSettings(await configureSacDigitalMenu(organizationId,settings));setNotice('Menu salvo.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o menu.');}finally{setBusy(false);}};
 return <section className="space-y-3 rounded border border-border p-4"><h2 className="font-bold">Menus personalizados</h2><label className="flex gap-2 text-sm"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Ativar menu</label><label className="block text-sm">Mensagem<textarea className="admin-input w-full rounded border p-2" value={settings.text} onChange={e=>setSettings({...settings,text:e.target.value})}/></label><label className="block text-sm">Origem das opções<select className="admin-input w-full rounded border p-2" value={settings.source} onChange={e=>setSettings({...settings,source:e.target.value as SacDigitalMenuSettings['source']})}><option value="static">Opções configuradas</option><option value="service_order_status">Status da ordem de serviço</option></select></label>{settings.source==='static'&&<div className="space-y-2">{settings.choices.map((choice,index)=><div key={index} className="flex gap-2"><input aria-label="Identificador da opção" placeholder="Identificador" className="admin-input min-w-0 rounded border p-2" value={choice.tag} onChange={e=>setSettings({...settings,choices:settings.choices.map((c,i)=>i===index?{...c,tag:e.target.value}:c)})}/><input aria-label="Texto da opção" placeholder="Texto" className="admin-input min-w-0 flex-1 rounded border p-2" value={choice.text} onChange={e=>setSettings({...settings,choices:settings.choices.map((c,i)=>i===index?{...c,text:e.target.value}:c)})}/><BtnSecondary onClick={()=>setSettings({...settings,choices:settings.choices.filter((_,i)=>i!==index)})}>Remover</BtnSecondary></div>)}<BtnSecondary onClick={()=>setSettings({...settings,choices:[...settings.choices,{tag:'',text:''}]})}>Adicionar opção</BtnSecondary></div>}<AdminButton loading={busy} onClick={()=>void save()}>Salvar menu</AdminButton>{token&&<label className="block text-sm">URL privada do menu<input readOnly value={sacDigitalMenuUrl(token)} className="admin-input w-full rounded border p-2"/></label>}{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}{health&&<div className="text-sm"><h3 className="font-semibold">Saúde da sincronização</h3>{Object.entries(health).filter(([,value])=>typeof value==='number'||typeof value==='string').map(([name,value])=><p key={name}>{name.replace(/_/g,' ')}: {String(value)}</p>)}</div>}</section>;
}
