import { useState } from "react";
import { AlertCircle, CheckCircle, ChevronRight, Clock, Package, X } from "lucide-react";
import { useServiceDetailBySlug } from "@/lib/hooks";
import { publicMediaUrl } from "@/features/public-catalog/infrastructure/public-media";
import type { PublicPage } from "@/features/public-shell/domain/navigation";
import { WhatsAppAction } from "@/features/public-shell/presentation/PublicShell";
import { PublicButton as Btn, PublicHeading as H2, SectionLabel } from "@/features/public-shell/presentation/PublicUi";

export function ServiceDetailPage({ slug, setPage }: { slug: string | null; setPage: (page: PublicPage) => void }) {
  const { detail, loading, error } = useServiceDetailBySlug(slug);
  const imageUrl = publicMediaUrl(detail?.media);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  if (loading) return <div className="min-h-[55vh] flex items-center justify-center text-[#5a6a82] text-sm"><Clock size={20} className="animate-spin mr-2 text-[#0057e7]" /> Carregando serviço...</div>;
  if (error) return <section className="py-20 bg-[#f5f7fa]"><div className="max-w-xl mx-auto px-4 text-center"><AlertCircle size={34} className="mx-auto mb-4 text-red-500" /><H2 className="mb-3">Não foi possível carregar este serviço</H2><p className="text-sm text-[#5a6a82] mb-6">{error}</p><Btn onClick={() => setPage("servicos")}>Voltar para serviços</Btn></div></section>;
  if (!detail) return <section className="py-20 bg-[#f5f7fa]"><div className="max-w-xl mx-auto px-4 text-center"><Package size={34} className="mx-auto mb-4 text-[#0057e7]" /><H2 className="mb-3">Serviço não encontrado</H2><p className="text-sm text-[#5a6a82] mb-6">O serviço solicitado não existe ou não está disponível no momento.</p><Btn onClick={() => setPage("servicos")}>Ver serviços disponíveis</Btn></div></section>;

  const { service, category, brand, product, variants, inclusions, exclusions, priceFactors, faqs, sections, filters } = detail;
  const formattedBasePrice = service.base_price ? `R$ ${Number(service.base_price).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}` : null;
  const priceLabel = service.price_mode === "HIDDEN" ? null : service.price_mode === "STARTING_FROM" && formattedBasePrice ? `A partir de ${formattedBasePrice}` : service.price_mode === "FIXED" && formattedBasePrice ? formattedBasePrice : "Consulte o valor";

  return <>
    <div className="bg-white border-b border-[#0d1b2e]/10"><div className="max-w-7xl mx-auto px-4 sm:px-6 py-3 flex items-center gap-2 text-xs text-[#5a6a82]"><button onClick={() => setPage("home")} className="hover:text-[#0057e7]">Início</button><ChevronRight size={12} /><button onClick={() => setPage("servicos")} className="hover:text-[#0057e7]">Serviços</button><ChevronRight size={12} /><span className="font-medium text-[#0d1b2e] truncate">{service.title}</span></div></div>
    <section className="bg-[#0d1b2e] py-12 sm:py-16"><div className="max-w-7xl mx-auto px-4 sm:px-6 grid lg:grid-cols-2 gap-10 items-center"><div><SectionLabel light>{category?.name || "Serviço"}</SectionLabel><h1 className="text-4xl sm:text-5xl font-black text-white leading-tight mb-4" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>{service.title}</h1>{service.short_description && <p className="text-white/70 text-base leading-relaxed mb-5">{service.short_description}</p>}{priceLabel && <p className="text-2xl font-black text-white mb-6">{priceLabel}</p>}<div className="flex flex-wrap gap-3"><Btn onClick={() => setPage("orcamento")}>Solicitar orçamento</Btn><WhatsAppAction /></div>{(brand?.name || product?.name) && <p className="text-xs text-white/60 mt-5">{brand?.name && `Marca: ${brand.name}`}{brand?.name && product?.name && " · "}{product?.name && `Produto: ${product.name}`}</p>}</div>{imageUrl && <div className="rounded-xl overflow-hidden border border-white/10"><img src={imageUrl} alt={service.title} className="w-full h-64 sm:h-80 object-cover" /></div>}</div></section>
    {(service.description || inclusions.length > 0 || exclusions.length > 0) && <section className="py-14 bg-[#f5f7fa]"><div className="max-w-5xl mx-auto px-4 sm:px-6 grid md:grid-cols-2 gap-10"><div>{service.description && <><SectionLabel>Sobre o serviço</SectionLabel><H2 className="mb-4">Sobre este serviço</H2><p className="text-sm text-[#5a6a82] leading-relaxed whitespace-pre-line">{service.description}</p></>}</div><div className="space-y-7">{inclusions.length > 0 && <div><SectionLabel>Incluso</SectionLabel><H2 className="mb-4">O que está incluso</H2><ul className="space-y-3">{inclusions.map((item: any) => <li key={item.id} className="flex gap-2 text-sm text-[#3a4a5e]"><CheckCircle size={16} className="text-[#0057e7] mt-0.5 shrink-0" />{item.description}</li>)}</ul></div>}{exclusions.length > 0 && <div><SectionLabel>Não incluso</SectionLabel><H2 className="mb-4">O que não está incluso</H2><ul className="space-y-3">{exclusions.map((item: any) => <li key={item.id} className="flex gap-2 text-sm text-[#3a4a5e]"><X size={16} className="text-red-500 mt-0.5 shrink-0" />{item.description}</li>)}</ul></div>}</div></div></section>}
    {variants.length > 0 && <section className="py-14 bg-white"><div className="max-w-5xl mx-auto px-4 sm:px-6"><SectionLabel>Variações</SectionLabel><H2 className="mb-8">Opções e valores</H2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{variants.map((variant: any) => <div key={variant.id} className="border border-[#0d1b2e]/10 rounded-xl p-5"><p className="font-bold text-[#0d1b2e]">{variant.title}</p>{variant.description && <p className="text-xs text-[#5a6a82] mt-2">{variant.description}</p>}<p className="text-lg font-black text-[#0057e7] mt-4">{variant.price ? `R$ ${Number(variant.price).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}` : "Consulte"}</p></div>)}</div></div></section>}
    {priceFactors.length > 0 && <section className="py-14 bg-[#f5f7fa]"><div className="max-w-5xl mx-auto px-4 sm:px-6"><SectionLabel>Transparência</SectionLabel><H2 className="mb-8">O que pode alterar o valor?</H2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{priceFactors.map((factor: any) => <div key={factor.id} className="bg-white border border-[#0d1b2e]/10 rounded-xl p-4"><p className="font-bold text-[#0d1b2e] text-sm">{factor.name}</p>{factor.description && <p className="text-xs text-[#5a6a82] mt-1">{factor.description}</p>}</div>)}</div></div></section>}
    {filters.length > 0 && <section className="py-10 bg-white"><div className="max-w-5xl mx-auto px-4 sm:px-6"><SectionLabel>Características</SectionLabel><div className="flex flex-wrap gap-2">{filters.map((filter: any) => <span key={filter.id} className="bg-[#e8eef8] text-[#0d1b2e] text-xs font-semibold px-3 py-1.5 rounded-md">{filter.name || filter.value}</span>)}</div></div></section>}
    {sections.map((section: any) => <section key={section.id} className="py-14 bg-white"><div className="max-w-5xl mx-auto px-4 sm:px-6"><SectionLabel>Informações</SectionLabel><H2 className="mb-4">{section.title}</H2><p className="text-sm text-[#5a6a82] leading-relaxed whitespace-pre-line">{section.content}</p></div></section>)}
    {faqs.length > 0 && <section className="py-14 bg-white"><div className="max-w-3xl mx-auto px-4 sm:px-6"><SectionLabel>Dúvidas</SectionLabel><H2 className="mb-8">Dúvidas frequentes</H2><div className="space-y-3">{faqs.map((faq: any, index: number) => <div key={faq.id} className="border border-[#0d1b2e]/10 rounded-xl overflow-hidden"><button onClick={() => setOpenFaq(openFaq === index ? null : index)} className="w-full flex justify-between gap-4 px-5 py-4 text-left hover:bg-[#f5f7fa]"><span className="font-semibold text-sm text-[#0d1b2e]">{faq.question}</span><ChevronDown size={16} className={openFaq === index ? "rotate-180 text-[#0057e7]" : "text-[#0057e7]"} /></button>{openFaq === index && <p className="px-5 pb-4 text-sm text-[#5a6a82] leading-relaxed">{faq.answer}</p>}</div>)}</div></div></section>}
    <section className="py-16 bg-[#0057e7]"><div className="max-w-3xl mx-auto px-4 text-center"><h2 className="text-3xl sm:text-5xl font-black text-white mb-4" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>Precisa deste serviço?</h2><div className="flex flex-wrap justify-center gap-4"><Btn className="bg-white text-[#0057e7] hover:bg-[#f0f6ff]" onClick={() => setPage("orcamento")}>Solicitar orçamento</Btn><WhatsAppAction /></div></div></section>
  </>;
}

