export const queryKeys = {
  publicSite: {
    all: ["public-site"] as const,
    settings: () => ["public-site", "settings"] as const,
    services: () => ["public-site", "services"] as const,
    serviceById: (serviceId: string) => ["public-site", "services", "id", serviceId] as const,
    service: (slug: string) => ["public-site", "services", slug] as const,
    categories: () => ["public-site", "categories"] as const,
    products: () => ["public-site", "products"] as const,
    featuredProducts: () => ["public-site", "products", "featured"] as const,
    product: (slug: string) => ["public-site", "products", slug] as const,
    brands: () => ["public-site", "brands"] as const,
    media: (mediaId: string) => ["public-site", "media", mediaId] as const,
  },
  admin: {
    all: ["admin"] as const,
    dashboard: (periodDays = 30, accessScope = "default") => ["admin", "dashboard", periodDays, accessScope] as const,
  },
  customers: {
    all: ["customers"] as const,
    lists: () => ["customers", "list"] as const,
    history: (customerId: string) => ["customers", "history", customerId] as const,
  },
  registrations: {
    all: ["registrations"] as const,
    lists: () => ["registrations", "list"] as const,
    list: (organizationId: string) => ["registrations", "list", organizationId] as const,
    details: () => ["registrations", "detail"] as const,
    detail: (organizationId: string, registrationId: string) => ["registrations", "detail", organizationId, registrationId] as const,
    contactsAll: ["registrations", "contacts"] as const,
    contacts: (organizationId: string, registrationId: string) => ["registrations", "contacts", organizationId, registrationId] as const,
    recordsAll: ["registrations", "records"] as const,
    records: (organizationId: string, registrationId: string) => ["registrations", "records", organizationId, registrationId] as const,
    supplierItemsAll: ["registrations", "supplier-items"] as const,
    supplierItems: (organizationId: string, registrationId: string) => ["registrations", "supplier-items", organizationId, registrationId] as const,
    accessAll: ["registrations", "access"] as const,
    access: (organizationId: string, employeeId: string) => ["registrations", "access", organizationId, employeeId] as const,
    permissionsAll: ["registrations", "permissions"] as const,
    permissions: (organizationId: string, userId: string) => ["registrations", "permissions", organizationId, userId] as const,
  },
  checklists: {
    all: ["checklists"] as const,
    profiles: () => ["checklists", "profiles"] as const,
    profile: (profileId: string) => ["checklists", "profile", profileId] as const,
    equipmentAll: ["checklists", "equipment"] as const,
    equipment: (equipmentTypeId: string) => ["checklists", "equipment", equipmentTypeId] as const,
    ordersAll: ["checklists", "orders"] as const,
    order: (orderId: string) => ["checklists", "orders", orderId] as const,
  },
  equipment: {
    all: ["equipment"] as const,
    catalog: () => ["equipment", "catalog"] as const,
    technicalFields: (equipmentTypeId: string) => ["equipment", "technical-fields", equipmentTypeId] as const,
  },
  generalServices: {
    all: ["general-services"] as const,
    lists: () => ["general-services", "list"] as const,
  },
  serviceTypes: {
    all: ["service-types"] as const,
    configuration: () => ["service-types", "configuration"] as const,
  },
  inventory: {
    all: ["inventory"] as const,
    lists: () => ["inventory", "list"] as const,
    active: () => ["inventory", "active"] as const,
    movements: (itemId: string) => ["inventory", "movements", itemId] as const,
  },
  finance: {
    all: ["finance"] as const,
    foundation: (organizationId: string) => ["finance", "foundation", organizationId] as const,
    accounts: (organizationId: string) => ["finance", "accounts", organizationId] as const,
    balances: (organizationId: string) => ["finance", organizationId, "balances"] as const,
    movements: (organizationId: string) => ["finance", organizationId, "movements"] as const,
    transfers: (organizationId: string) => ["finance", organizationId, "transfers"] as const,
    categories: (organizationId: string) => ["finance", "categories", organizationId] as const,
    costCenters: (organizationId: string) => ["finance", "cost-centers", organizationId] as const,
    paymentMethods: (organizationId: string) => ["finance", "payment-methods", organizationId] as const,
    settings: (organizationId: string) => ["finance", "settings", organizationId] as const,
    entries: (organizationId: string, type: "payable" | "receivable") => ["finance", organizationId, "entries", type] as const,
    entry: (organizationId: string, id: string) => ["finance", organizationId, "entry", id] as const,
    settlements: (organizationId: string, id: string) => ["finance", organizationId, "settlements", id] as const,
    approvals: (organizationId: string, id: string) => ["finance", organizationId, "approvals", id] as const,
    pendingApprovals: (organizationId: string) => ["finance", organizationId, "pending-approvals"] as const,
    counterparties: (organizationId: string, type: "payable" | "receivable") => ["finance", organizationId, "counterparties", type] as const,
    cashSessions: (organizationId: string) => ["finance", organizationId, "cash-sessions"] as const,
    recurring: (organizationId: string) => ["finance", organizationId, "recurring"] as const,
    attachments: (organizationId: string, entryId: string) => ["finance", organizationId, "attachments", entryId] as const,
    collections: (organizationId: string, entryId: string) => ["finance", organizationId, "collections", entryId] as const,
    scheduledSettlements: (organizationId: string) => ["finance", organizationId, "scheduled-settlements"] as const,
    dashboard: (organizationId: string, from: string, to: string) =>
      ["finance", organizationId, "dashboard", from, to] as const,
    dre: (organizationId: string, from: string, to: string, categoryId: string, costCenterId: string, originType: string) =>
      ["finance", organizationId, "reports", "dre", from, to, categoryId, costCenterId, originType] as const,
    cashFlow: (
      organizationId: string,
      from: string,
      to: string,
      accountId: string,
      categoryId: string,
      costCenterId: string,
      originType: string,
      paymentMethodId: string,
    ) => ["finance", organizationId, "reports", "cash-flow", from, to, accountId, categoryId, costCenterId, originType, paymentMethodId] as const,
  },
  appointments: {
    all: ["appointments"] as const,
    lists: () => ["appointments", "list"] as const,
    list: (scope: { userId: string | null; canViewOtherAgendas: boolean }) =>
      ["appointments", "list", scope] as const,
  },
  quotes: {
    all: ["quotes"] as const,
    lists: () => ["quotes", "list"] as const,
  },
  employees: {
    all: ["employees"] as const,
    lists: () => ["employees", "list"] as const,
    roles: () => ["employees", "roles"] as const,
  },
  catalog: {
    all: ["catalog"] as const,
    services: () => ["catalog", "services"] as const,
    products: () => ["catalog", "products"] as const,
    brands: () => ["catalog", "brands"] as const,
    categories: () => ["catalog", "categories"] as const,
  },
  orderSituations: {
    all: ["order-situations"] as const,
    lists: () => ["order-situations", "list"] as const,
  },
  orderStatuses: {
    all: ["order-statuses"] as const,
    lists: () => ["order-statuses", "list"] as const,
  },
  orders: {
    all: ["orders"] as const,
    workspace: () => ["orders", "workspace"] as const,
    lists: () => ["orders", "list"] as const,
    list: (filters: Record<string, unknown>) => ["orders", "list", filters] as const,
    details: () => ["orders", "detail"] as const,
    detail: (orderId: string) => ["orders", "detail", orderId] as const,
    partRequests: (orderId: string) => ["orders", "part-requests", orderId] as const,
    media: (orderId: string) => ["orders", "media", orderId] as const,
  },
} as const;
